version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    networks:
      - user-api-network
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - user-api-network
    environment:
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
      - spring.datasource.url=jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.generate-ddl=true
      - spring.jpa.show-sql=false
networks:
  user-api-network: